### ISSUE TITLE
Unable to use jdenticon in Nodejs

### ISSUE THREAD

**Issue by XEonAX** [dmester/jdenticon#17]
I am getting 
```
TypeError: Cannot set property 'requirejsVars' of undefined
    at j:\ROOT\BITSProject\jar-web\node_modules\requirejs\bin\r.js:2399:24
    at Object.<anonymous> (j:\ROOT\BITSProject\jar-web\node_modules\requirejs\bin\r.js:28749:2)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (j:\ROOT\BITSProject\jar-web\node_modules\jdenticon\index.js:39:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
```

which is caused by https://github.com/requirejs/requirejs/issues/1681

Is there any workaround for the same?

**Comment by dmester** [comment]
Do you run your application in strict mode e.g. by using the `--use-strict` switch on Node? Unfortunately requirejs does not seem to play well when strict mode is enabled globally.

# Workarounds
These are the three simpliest workarounds I can think of: 

## Alternative 1
Patch Jdenticon to not use the requirejs loaded source files.

In Jdenticon **index.js:39**, replace:
```js
var requirejs = require("requirejs");
var path = require("path");

requirejs.config({    
    baseUrl: path.join(__dirname, "src"),
    nodeRequire: require
});

var jdenticon = requirejs("jdenticon");
```

with

```js
var jdenticon = require("./dist/jdenticon.js");
```

## Alternative 2
In your application, use the combined jdenticon lib from the dist folder. This is not complete and lacks support for PNG export.

Use:
```js
var jdenticon = require("./node_modules/jdenticon/dist/jdenticon.js");
```
instead of
```js
var jdenticon = require("jdenticon");
```

## Alternative 3
Don't use strict mode globally.

## Why is requirejs used at all?
The reason requirejs was introduced in the Jdenticon Node package was to allow using the source code without relying on the combined script files in the dist folder.

**Comment by XEonAX** [comment]
Alternative 2 solved my problem. 
Thanks
